### ISSUE TITLE
[Feature Request] Time Input Conversion

### ISSUE THREAD

**Issue by colcrunch** [ppfeufer/aa-timezones#10]
I know that it is possible to convert time by adding a URL query parameter containing a time epoch value, but it could be very useful for planning purposes to include a date/time picker (from the user's local time) to allow converting timezones on the fly.

**Comment by ppfeufer** [comment]
You mean something like this one? (click the adjust time button below the time zone panels)

![Selection_294](https://user-images.githubusercontent.com/2989985/82115967-7f836f80-9766-11ea-96bc-4881904ef519.jpg)

**Comment by colcrunch** [comment]
Oh, I didn't eve see that xD

**Comment by ppfeufer** [comment]
No problem, I made the buttons a bit larger with v0.1.4 :-)
