### ISSUE TITLE
(Feature Request) Show Time Until in "Set Mode"

### ISSUE THREAD

**Issue by pvyParts** [ppfeufer/aa-timezones#19]
Would be awesome if the app counted down in the "set" mode.
Maybe here or here, but i'll leave that up to you!
![Imgur](https://i.imgur.com/yIlXNL6.png)

**Comment by ppfeufer** [comment]
There ya go

![2992a8bd72f4](https://user-images.githubusercontent.com/2989985/85389634-fd961b80-b547-11ea-96b2-525a82d0f13c.jpg)

**Comment by pvyParts** [comment]
So awesome!
