### ISSUE TITLE
Redirect Loop

### ISSUE THREAD

**Issue by Aimsucks** [ppfeufer/aa-timezones#32]
When you click the link without being logged in, you enter a redirect loop and can't access the link without first visiting the auth site and logging in.

1. `https://auth.example.com/timezones/1603155600/`
2. redirected to
3. `https://auth.example.com/account/login/?next=/timezones/1603155600/`
4. click login
5. `https://login.eveonline.com/oauth/authorize/?response_type=code&client_id=XXX&redirect_uri=https%3A%2F%2Fauth.example.com%2Fsso%2Fcallback&scope=publicData&state=XXX`
6. click authorize
7. `https://auth.example.com/account/login/?next=/timezones/1603155600/`
8. click login
9. `https://login.eveonline.com/oauth/authorize/?response_type=code&client_id=XXX&redirect_uri=https%3A%2F%2Fauth.example.com%2Fsso%2Fcallback&scope=publicData&state=XXX`
10. click authorize
11. `https://auth.example.com/account/login/?next=/timezones/1603155600/`
12. repeating from step 3

This was my experience. Is it something on my end, or something to do with the plugin? None of my other apps cause this to happen.

**Comment by ppfeufer** [comment]
From Discord (for the records):

> rdax
> That soneome probably doesn't have the "Can access" permission
> 
> Aimsucks
> oh
> wow that's odd. they can see it on the front page
> 
> rdax
> But that seems some other fuckery to be going on there
> Just tested, with and without permissions
> You always land on the dashboard, because this parameter > ?next=/timezones/1603155600/ is ignored as it seems
> Teste with timezones, tested wit fatlinks, tested with any link from the left menu, they all are ignored
> So you seem to have an issue with the login itself
> Check your logs
> 
> Aimsucks
> yeah I'll check tomorrow
> very weird
> feel free to close my issue
